apiVersion: v1
kind: Service
metadata:
  name: my-python-app
  namespace: mina
spec:
  type: NodePort
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 8080        # Bu, servisin Kubernetes içindeki portudur.
      targetPort: 8080  # Bu, pod içindeki portudur.
      nodePort: 32000   # Bu, node üzerindeki portudur.

