apiVersion: v1
kind: Service
metadata:
  name: my-python-app
  namespace: mina
spec:
  type: NodePort
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 5000        # Bu, servisin Kubernetes içindeki portudur.
      targetPort: 5000  # Bu, pod içindeki portudur.
      nodePort: 32000   # Bu, node üzerindeki portudur.

